### ISSUE TITLE
Instant tracking not working on Android

### ISSUE THREAD

**Issue by marioslokas** [zappar-xr/zappar-unity-examples#10]
Hi,

Most examples are working fine, except for the Instant Tracking one on Android (iOS sort of worked, it just took some time to find the place). Camera turns on, I can see the bot anchored on the camera, but plane detection never works and the model cannot be placed anywhere.

I built the examples with Unity version 2019.4.7f1.

Edit: It actually works, however not in the least in a satisfactory way. I am getting 5-10 frames and very bad tracking accuracy in a rather beefy Android device. It seems the model floats away every time it gets a bit out of view.

**Comment by cw-chlim-nm** [comment]
In my case it didn't work on iOS, either.  Also the character was being rendered upside down, like it was mirrored in some way.

**Comment by nfynt-zap** [comment]
Hi,

I would point you to the following article: https://forum.zap.works/t/introducing-instant-tracking/5396 which goes in detail about what you can expect from instant tracking on Web. Especially the sections: "What’s the difference between World Tracking and Instant Tracking?" and "Any downsides?". 

Otherwise we have done some great updates to unity package over the past year so do check out the new package and the example repos!

Cheers,
